export { default as TheDestruction } from './the-destruction/TheDestruction.vue';
export { default as TheAlteration } from './the-alteration/TheAlteration.vue';
export { default as TheConjuration } from './the-conjuration/TheConjuration.vue';
export { default as TheIllusion } from './the-illusion/TheIllusion.vue';
export { default as TheRestoration } from './the-restoration/TheRestoration.vue';
export { default as TheEnchanting } from './the-enchanting/TheEnchanting.vue';
export { default as TheShouts } from './the-shouts/TheShouts.vue';
export { default as TheSpellbook } from './the-spellbook/TheSpellbook.vue';
export { default as ThePowers } from './the-powers/ThePowers.vue';
